---
abstract: 'Rapidly propagate (rsync/scp/...) files to many servers in multiple locations.'
author:
  - 'Alex White <VVu@geekfarm.org>'
generated_by: 'Dist::Zilla version 1.093280'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-CascadeCopy
requires:
  Benchmark: 0
  Class::Std::Utils: 0
  Data::Dumper: 0
  ExtUtils::MakeMaker: 0
  Getopt::Long: 0
  Log::Log4perl: 0
  POSIX: 0
  Pod::Usage: 0
  Proc::Queue: 0
  Test::Differences: 0
  Test::More: 0
  vars: 0
version: 0.2.4
