# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-CascadeCopy
version:      v0.0.3
version_from: lib/Net/CascadeCopy.pm
installdirs:  site
requires:
    Getopt::Long:                  0
    Log::Log4perl:                 0
    Pod::Usage:                    0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
